# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging_loki/loki_push.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'logging_loki/loki_push.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1clogging_loki/loki_push.proto\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\".\n\x0bPushRequest\x12\x1f\n\x07streams\x18\x01 \x03(\x0b\x32\x0e.StreamAdapter\"M\n\rStreamAdapter\x12\x0e\n\x06labels\x18\x01 \x01(\t\x12\x1e\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\r.EntryAdapter\x12\x0c\n\x04hash\x18\x03 \x01(\x04\"\xb9\x01\n\x0c\x45ntryAdapter\x12\x1d\n\ttimestamp\x18\x01 \x01(\x0b\x32\n.Timestamp\x12\x0c\n\x04line\x18\x02 \x01(\t\x12\x41\n\x12structuredMetadata\x18\x03 \x03(\x0b\x32%.EntryAdapter.StructuredMetadataEntry\x1a\x39\n\x17StructuredMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_loki.loki_push_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTRYADAPTER_STRUCTUREDMETADATAENTRY']._loaded_options = None
  _globals['_ENTRYADAPTER_STRUCTUREDMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_TIMESTAMP']._serialized_start=32
  _globals['_TIMESTAMP']._serialized_end=75
  _globals['_PUSHREQUEST']._serialized_start=77
  _globals['_PUSHREQUEST']._serialized_end=123
  _globals['_STREAMADAPTER']._serialized_start=125
  _globals['_STREAMADAPTER']._serialized_end=202
  _globals['_ENTRYADAPTER']._serialized_start=205
  _globals['_ENTRYADAPTER']._serialized_end=390
  _globals['_ENTRYADAPTER_STRUCTUREDMETADATAENTRY']._serialized_start=333
  _globals['_ENTRYADAPTER_STRUCTUREDMETADATAENTRY']._serialized_end=390
# @@protoc_insertion_point(module_scope)
