name: "Loki Logging Benchmark"

on:
  workflow_dispatch:

env:
  LOKI_URL: ${{secrets.LOKI_URL}}
  LOKI_USERNAME: ${{secrets.LOKI_USERNAME}}
  LOKI_PASSWORD: ${{secrets.LOKI_PASSWORD}}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: setup packages
        run: pip install -U pip && pip install psutil && pip install -e .

      - name: Run
        env:
          LOKI_LOGGING_DEBUG: "TRUE"
        run: python tests/benchmark.py

      - name: result
        run: cat AA_rest_agv.txt